blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('',views.PostList.as_view()),
    path('<int:pk>/',views.PostDetail.as_view()),
    path('category/<str:slug>/',views.category_page),
    path('tag/<str:slug>/',views.tag_page),
    path('create_post/',views.PostCreate.as_view()),
    path('update_post/<int:pk>/',views.PostUpdate.as_view()),
    path('<int:pk>/new_comment/',views.new_comment),
    path('update_comment/<int:pk>/',views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/',views.delete_comment),
    path('search/<str:q>/',views.PostSearch.as_view()), #검색어에 해당하는 값을 문자열로 받고 그 값을 q라고 부르겠다는 의미이다.
]

wanje1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('markdownx/',include('markdownx.urls')), #마크다운을 사용하기위해 url을 설정해야된다. 그리고 textfield를 markdownxfield로 바꾸면 된다.
    path('accounts/',include('allauth.urls')),# django-allauth가 사용할 수 있는 url경로를 추가한다. 그리고 migrate만 입력해서 데이터베이스에 반영도 해야된다.
    path('',include('single_pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown #화면에 포스트를 렌더링할때 마크다운 기능이 나타나게 할려면 마크다운 문법으로 
                                        #작성된 content필드값을 html로 변환하는 작업이 필요하다.
import os
# Create your models here.
class Tag(models.Model): #post 위에 추가 해야된다
    name=models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True) #slug는 한글적용이 자동으로 안되서 allow_unicode를 해줘야된다

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/' #f string이란 방법인데 format이랑 똑같다.{}안에 특정 변수를 넣는다.

class Category(models.Model): #post 위에 추가 해야된다
    name=models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/' #f string이란 방법인데 format이랑 똑같다.
    

    class Meta:
        verbose_name_plural='Categories'

class Post(models.Model):
    title=models.CharField(max_length=30, verbose_name='제목')
    content=MarkdownxField()
    hook_text=models.CharField(max_length=100,blank=True, verbose_name='요약문')
    created_at=models.DateTimeField(auto_now_add=True,verbose_name='생성시간')
    updated_at=models.DateTimeField(auto_now=True,verbose_name='변경시간')
    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags=models.ManyToManyField(Tag, blank=True)


    def __str__(self):
        return f'[{self.pk}{self.title}] :: {self.author}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/' #pk는 primary key로 자동으로 생성

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]

    def get_content_markdown(self):
        return markdown(self.content) #마크다운 문법으로 작성된content 모델을 html로 보이게 전환한다.
                                        #템플릿에서 get_content_markdown을 입력해서 적용시킨다.

class Comment(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    content=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}' #어드민에서 view on site를 눌리면 해당 댓글을 바로 볼 수 있다. 여기가 잘 이해가 안되긴 하다

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url() #로그인 계정의 아바타 url을 가져온다.
        else:
            return f'https://doitdjango.com/avatar/id/25/818036b33e566bc0/svg/{self.author.email}'

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',) # Comment모델에서 content만 폼으로 불러온다는 뜻이다. 템플릿에 content 모델만 출력된다.
                                #fields대신 exclude를 쓸 수 있다. exclude는 제외할 모델을 선택한다. 그 모델 말고는 모든 모델을 폼으로 불러온다는뜻이다. 
                                # 자세한 내용은 475쪽 476쪽 참조.

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post, Category, Tag, Comment
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.db.models import Q #여러 쿼리를 동시에 써야할때는 장고에서 제공하는 Q를 사용한다.

# Create your views here.

class PostList(ListView):
    model=Post
    template_name='blog/blog_list.html'
    ordering='-pk'
    paginate_by=5 #한페이지에 5개의 포스트만 보여준다. page_obj를 템플릿에서 이용하면 된다. pg 507참조
                #url로 /blog/?page=페이지번호를 입력했을때 어떤 페이지를 보여줄지 urls.py에 두지 않아도 괜찮다. 
                #장고에서 자동으로 page값에 맞는 포스트를 불러오는 쿼리를 작동시키도록 되어있다.


    def get_context_data(self, **kwargs):
        context = super(PostList,self).get_context_data()
        context['categories']=Category.objects.all()
        context['no_category_post_count']=Post.objects.filter(category=None).count()
        return context

class PostDetail(DetailView):
    model=Post
    template_name='blog/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super(PostDetail,self).get_context_data()
        context['categories']=Category.objects.all()
        context['no_category_post_count']=Post.objects.filter(category=None).count()
        context['comment_form']=CommentForm # CommentForm을 comment_form이라는 이름으로 템플릿으로 넘긴다.(폼에서 content 모델만 넘어온다)
        return context


def category_page(request, slug): #url에서 slug를 받아온다.
    if slug =='no_category':
        category='미분류'
        post_list=Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list=Post.objects.filter(category=category)
    
    return render(
        request,
        'blog/blog_list.html',
        {
            'post_list':post_list.order_by('-pk'), #pk랑 id 둘다 써도 된다
            'categories':Category.objects.all(),
            'no_category_post_count':Post.objects.filter(category=None).count(),
            'category':category,

        }
    )

def tag_page(request, slug): #url에서 slug를 받아온다.
    tag = Tag.objects.get(slug=slug)
    post_list=tag.post_set.all()

    
    return render(
        request,
        'blog/blog_list.html',
        {
            'post_list':post_list.order_by('-pk'), #pk랑 id 둘다 써도 된다
            'tag':tag,
            'categories':Category.objects.all(),
            'no_category_post_count':Post.objects.filter(category=None).count()
            

        }
    )

class PostCreate(LoginRequiredMixin,UserPassesTestMixin,CreateView):   #로그인믹신을 먼저 써야된다.
    model=Post
    fields=['title','hook_text','content','head_image','file_upload','category']
    template_name='blog/post_form.html'

    def test_func(self): #스태프 권한이 지정되어야만 글을 쓸 수 있다.
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form): # 로그인을 해야지 글을 쓸 수 있는 기능만들기. authenticated +tag추가
        current_user=self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user #모델에 author을 currentuser로 자동으로 저장한다.
            response=super(PostCreate,self).form_valid(form)

            tags_str=self.request.POST.get('tags_str') #템플릿에서 name이 tags_str인 폼으로 들어온 데이터를 tags_str에 저장한다.
            if tags_str:
                tags_str=tags_str.strip() #앞뒤 공백제거
                tags_str=tags_str.replace(',',';') #,를 ;로 변환
                tags_list=tags_str.split(';') # ;를 기준으로 string을 쪼개서 list에 저장

                for t in tags_list:
                    t=t.strip()
                    tag,is_tag_created=Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug=slugify(t, allow_unicode=True) #unicode로 한글도 가능하게 한다. slug는 원래 한글을 지원하지 않는다.
                        tag.save()
                    self.object.tags.add(tag)
            
            return response
        
        else:
            return redirect('/blog/')

class PostUpdate(LoginRequiredMixin, UpdateView):   #로그인믹신을 먼저 써야된다.
    model=Post
    fields=['title','hook_text','content','head_image','file_upload','category']
    template_name='blog/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):   #방문자가 웹사이트 서버에 get 인지 post로 요청했는지 판단하는 기능
                                                    #만약 방문자가 서버에 get으로 들어오면 포스트를 작성할 수 있는 폼 페이지를 보내준다.
                                                    #반면에 post(버튼)로 들어오면 폼이 유효한지 확인하고 문제가 없으면 데이터베이스에 저장한다.
                                                    #만약 권한이 없는 사용자가 post update를 사용하려고 하면 접근을 못하게 해야된다.
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def get_context_data(self, **kwargs): #원래 저장되어있던 tags 불러오기
        context=super(PostUpdate,self).get_context_data()
        if self.object.tags.exists():           #만약에 그 인스턴스(포스트)에 tags가 존재하면
            tags_str_list=list()                
            for t in self.object.tags.all():    
                tags_str_list.append(t.name)    #즉 포스트에서 리스트형태로 저장된 태그스트링을 각각 다시 리스트로 넣는다.
            context['tags_str_default']='; '.join(tags_str_list) #그리고 join으로 ;를 경계로 string으로 합쳐준다.
                                                                #context에 tags_str_default로 채워서 템플릿에 쓸수 있게 반환한다.
        return context

    def form_valid(self, form): # tag 불러오고 저장하기, author은 그전에 저장되어있으므로 바꿀 필요가 없어 그에 관한 코드는 삭제한다.
        response=super(PostUpdate,self).form_valid(form)
        self.object.tags.clear() #포스트에서 가져온 태그들을 모두 삭제한다. 그리고 아래에서 다시 가져온다.

        tags_str=self.request.POST.get('tags_str') #템플릿에서 name이 tags_str인 폼(post)으로 들어온 데이터를 tags_str에 저장한다.
        if tags_str:
            tags_str=tags_str.strip() #앞뒤 공백제거
            tags_str=tags_str.replace(',',';') #,를 ;로 변환
            tags_list=tags_str.split(';') # ;를 기준으로 string을 쪼개서 list에 저장

            for t in tags_list:
                t=t.strip()
                tag,is_tag_created=Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug=slugify(t, allow_unicode=True) #unicode로 한글도 가능하게 한다. slug는 원래 한글을 지원하지 않는다.
                    tag.save()
                self.object.tags.add(tag)
        
        return response
    
def new_comment(request,pk):
    if request.user.is_authenticated: #로그인하지 않은 상태에서도 비정상적인 방법으로 댓글에 접근하려는 시도가 있을 수 있어
                                        #로그인하지 않은 경우 permission denied를 발생시킨다.
        post = get_object_or_404(Post, pk=pk) #new_comment 함수는 pk를 인자로 받는다. 이 값으로 댓글을 달 포스트를 쿼리를 날려 가져온다. 
                                                #해당하는 pk가 없는 경우에는 got_object_or_404로 404오류를 발생시킵니다.
        
        if request.method == 'POST': #포스트 방식 폼 버튼 즉 submit 버튼을 눌렀을 경우
            comment_form = CommentForm(request.POST) #포스트방식으로 들어온 정보를 commentform형식으로 가져옵니다.
            if comment_form.is_valid(): #폼이 유효하다면 해당 내용으로 새로운 레코드를 만들어 데이터베이스에 저장한다. 
                comment=comment_form.save(commit=False) #commit=False로 바로 모델에 저장하는것이 아니라 인스턴스만 가지고 온다.
                comment.post=post # comment_form은 content필드의 내용만 있으므로 post필드는 위에서 pk로 가져온 정보로 채웁니다.
                comment.author=request.user #author 필드는 로그인한 사용자 정보로 채웁니다.
                comment.save() #위의 작업들이 끝나면 저장을 합니다.
                return redirect(comment.get_absolute_url()) #마지막으로 comment의 url로 리다이렉트합니다. 
                #해당포스트의 상세페이지에서 이 댔글이 작성되어있는 위치로 브라우저가 이동합니다. 어떻게 이쪽으로 이동하는거지?

            else:
                return redirect(post.get_absolute_url()) #폼이 유효하지 않다면 다시 포스트 페이지로 돌아옵니다.

        else:
            raise PermissionDenied  #버튼을 클릭한게 아니라 url즉 get으로 들어온경우(~/pk/new_comment/) 요청을 거부합니다.



class CommentUpdate(LoginRequiredMixin, UpdateView):
    model=Comment
    form_class=CommentForm
    template_name='blog/comment_form.html'

    def dispatch(self, request, *args, **kwargs): #방문자가 edit버튼을 클릭해 이 페이지로 접근했다면 get 방식이므로 
                                                    #pk=1인 comment의 내용이 폼에 채워진 상태의 페이지가 나타납니다.
                                                    #summit 버튼을 클릭하면 /blog/update_comment/1/경로로 post방식을 사용해 폼의 내용을 전달한다
        if request.user.is_authenticated and request.user == self.get_object().author: #그리고 다른 사용자가 수정하는것을 막는다.
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url()) #그뒤로 댓글이 달린 post로 redirect한다
    else:
        raise PermissionDenied        

#아래 pg 518 참조
class PostSearch(PostList): #위에 만들었던 PostList를 상속받는다.
    paginate_by=10 #더 많이 볼 수 있게 10으로 설정합니다. 혹은 None으로 하면 페이지가 없이 모든 검색결과가 출력됩니다.

    def get_queryset(self): #model이 post이므로 get_queryset의 결과는 Post.objects.all()과 동일
        q=self.kwargs['q'] #url을 통해 넘어온 q라는 검색어를 받아 q라는 변수에 저장한다. 
        post_list = Post.objects.filter( #title__contain은 title.contains와 같은 의미이다. 
            Q(title__contains=q) | Q(tags__name__contains=q) #distinct()는 중복으로 가져온 요소가 있을때 한번만 나타나게 한다
                                                            #만약 태그와 제목 모두에서 python이 있으면 동일한 포스트를 다 출력한다.
        ).distinct() #PostSearch는 검색결과만 가지고 와야되므로 get_queryset()을 오버라이딩합니다. 즉 검색결과에 해당되는 포스트만 가지고 옵니다
        return post_list.order_by('-pk')

    def get_context_data(self,**kwargs): #PostList에 get_context_data()가 존재하지만 몇가지 인자를 추가하기 위해 오버라이딩한다.
        context=super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})' #템플릿에 쓸 search_info에 검색명과 개수만 넘기면 된다. 

        return context

blog/templates/blog/blog_list.html
{%extends 'blog/base.html'%}

{%block main_area%}

    {%if user.is_authenticated%}
        {%if user.is_superuser or user.is_staff%}
            <a class="btn btn-info btn-sm float-right" href="/blog/create_post" role='button' ><i class="fas fa-pen"></i>
            &nbsp;&nbsp;New Post</a>
        {%endif%}
    {%endif%}
    <h1>Blog
    {%if search_info%} <small class='text-muted'>{{search_info}}</small>{%endif%}
    {%if category%} <span class="badge bg-secondary">{{category}}</span>{%endif%}
        {%if tag%} <span class="badge bg-light"><i class="fas fa-tags"></i>{{tag}} ({{tag.post_set.count}})</span>{%endif%}</h1>
        {%if post_list.exists%}
            {%for p in post_list%}
            <div class="card mb-4" id='post-{{p.pk}}'>
            {%if p.head_image%}
                <img class="card-img-top" src={{p.head_image.url}} alt="{{p}} head image">
            {%else%}
                <img class="card-img-top" src='https://picsum.photos/seed/{{p.id}}/800/200' alt="random_image">

            {%endif%}
                <div class="card-body">
                <span class="badge bg-secondary float-right">{{p.category}}</span>
                <h2 class="card-title">{{p.title}}</h2>
                {%if p.hook_text%}  
                    <h5 class='text-muted'>{{p.hook_text}}</h5>
                {%endif%}
                <p class="card-text">{{p.get_content_markdown | truncatewords_html:35 | safe}}</p> 
                {% comment %} truncatewords_html로해야 html기준으로 35단어를 잘라준다. {% endcomment %}
                {%if p.tags.exists %}
                    <i class="fas fa-tags"></i>
                    {%for tag in p.tags.all%}
                        <a href="{{tag.get_absolute_url}}"><span class="badge rounded-pill bg-light text-dark">{{tag}}</span></a>
                    {%endfor%}
                    <br>
                    <br>
                {%endif%}
                <a href="{{p.get_absolute_url}}" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                Posted on {{p.created_at}}
                by<a href="#"> {{p.author | upper}}</a>
                </div>
            </div>
            {%endfor%}
        {%else%}
            <h3>아직 게시물이 없습니다.</h3>
        {%endif%}
        {% if is_paginated %}
        {% comment %} is_paginated를 쓴 이유는 만약 포스트 개수가 5개 이하면 필요가 없기 때문이다. {% endcomment %}
        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
            {%if page_obj.has_previous%} 
            {% comment %} page_obj를 이용해서 다음페이지나 이전페이지가 있는지 알아낸다. {% endcomment %}
                <li class="page-item">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}">&larr; Newer</a>
                </li>
            {%else%}
                <li class="page-item disabled">
                <a class="page-link" href="#">&larr; Newer</a>
                </li>
            {%endif%}
            
            {%if page_obj.has_next%}
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.next_page_number}}">Older &rarr;</a>
                </li>
            {%else%}
                <li class="page-item disabled">
                <a class="page-link" href="#">Older &rarr;</a>
                </li>
            {%endif%}


        </ul>
        {%endif%}
{%endblock%}

blog/templates/blog/comment_form.html
{%extends 'blog/base_full_width.html'%}
{% load crispy_forms_tags %}
{%block head_title%}
  Edit Comment - Blog
{%endblock%}
{%block main_area%}
    <h1>Edit Comment</h1>
    <hr>

    <form method='post' id='comment-form'>{% csrf_token %}
        {{form | crispy }}
        <br>
        <button type='submit' class='btn btn-primary float-right'>Submit</button>
    </form>
{%endblock%}

blog/templates/blog/post_detail.html
{%extends 'blog/base.html'%}
{%load crispy_forms_tags%} 
<!-- 폼 출력을 꾸며준다. -->
{%block head_title%}
  {{post.title}} - Blog
{%endblock%}
{%block main_area%}
  <div class='post-area'>
    <h1 class="mt-4">{{post.title}}</h1>
    <h5 class='text-muted'>{{post.hook_text}}</h5>
    <!-- Author -->
    <p class="lead">
      by
      <a href="#">{{post.author | upper}}</a>
    </p>

    <hr>

    {% if user.is_authenticated and user == post.author %}
      <a class='btn btn-info btn-sm float-right' href="/blog/update_post/{{post.pk}}/" role="button" ><i class="fas fa-pen"></i>
        Edit Post</a>
    {%endif%}

    <!-- Date/Time -->
    <p>{{post.created_at}}</p>

    <hr>

    <!-- Preview Image -->
    {%if post.head_image%}
        <img class="img-fluid rounded" src={{post.head_image.url}} alt="{{post}} head image">
    {%else%}
        <img class="img-fluid rounded" src='https://picsum.photos/seed/{{post.id}}/800/200' alt="random_image">


    {%endif%}
    <hr>

    <!-- Post Content -->
    <p>{{post.get_content_markdown | safe}}</p> 
    {% comment %} 모델에서 get_content_markdown함수로 markdown이 적용된 content필드를 가지고온다. 그리고 safe 필터로 이스케이핑을 방지한다.{% endcomment %}

    <hr>

    {%if post.tags.exists %}
        <i class="fas fa-tags"></i>
        {%for tag in post.tags.all%}
            <a href="{{tag.get_absolute_url}}"><span class="badge rounded-pill bg-light text-dark">{{tag}}</span></a>
        {%endfor%}
        <br>
        <br>
    {%endif%}

    {% if post.file_upload %}
        <a href="{{post.file_upload.url}}" type="button" class="btn btn-outline-dark" role="button" download>Download:
            {%if post.get_file_ext == 'csv' %}
                <i class="fas fa-file-csv"></i>
            {%elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls'%}
                <i class="fas fa-file-excel"></i>
            {%elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc'%}   
                <i class="fas fa-file-word"></i>
            {%else%}
                <i class="fas fa-file"></i>    
            {%endif%}
            {{post.get_file_name}}
        </a>
    {% endif %}
  </div>
    
    <!-- Comments Form -->
  <div id='comment-area'>
    <div class="card my-4">
      <h5 class="card-header">Leave a Comment:</h5>
      <div class="card-body">
        {%if user.is_authenticated%}
        <form id='comment-form' method='POST' action='{{post.get_absolute_url}}new_comment/'> 
          {% csrf_token %}
          <!--post.get_absolute_url= '/blog/{self.pk}/'  그래서 이 url과 연결된 new_comment fbv로 간다. 그리고 포스트의 pk를 받는다. -->
          <div class="form-group">
            <div id="div_id_content" class="form-group"> <label for="id_content" class=" requiredField">
              Content<span class="asteriskField">*</span> </label> <div class=""> <textarea name="content" cols="40" rows="5" class="textarea form-control" required id="id_content">
</textarea> </div> </div>
            <div></div> 
            <!-- 뷰에서 폼을 comment_form으로 넘겨받았다. -->
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        {%else%}
          <a role='button' class="btn btn-outline-dark btn-sm btn-block" href="#" data-toggle='modal' 
          data-target='#LoginModal'>Log in and leave a comment</a>

        {%endif%}
      </div>
    </div>
   
    <!-- Single Comment -->
     {% if post.comment_set.exists %}
        {% for comment in post.comment_set.iterator %}
        <div class="media mb-4" id='comment-{comment.pk}'>
          <img class="d-flex mr-3 rounded-circle" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width='60px'>
          <div class="media-body">
            {% if user.is_authenticated and comment.author == user %}
              <div class='float-right'>
                <a role='button' class='btn btn-sm btn-info' id='comment-{{comment.pk}}-update-btn'
                href="/blog/update_comment/{{comment.pk}}/">edit</a>
                <a role='button' href="#" id='comment-{{comment.pk}}-delete-modal-btn' class="btn btn-sm btn-danger"
                data-toggle='modal' data-target='#deleteCommentModal-{{comment.pk}}'>delete</a>
                <!-- id는 그냥 모달을 표현하는거다. 중요한거는 data-target이다. 이게 작동할려면 data-target과 동일한 id를 가진 div가 존재해야된다. -->
              </div>
            {% endif %}
            <h5 class="mt-0">{{comment.author.username}} &nbsp;&nbsp;<small class='text-muted'>{{comment.created_at}}</small></h5>
           <p>{{comment.content | linebreaks}}</p> 
           <!-- linebreaks로 줄바꿈이 가능하게 한다. -->
          </div>
          <!-- Modal -->
          <div class='modal fade' id='deleteCommentModal-{{comment.pk}}' tabindex='-1' role='idalog' 
          aria-labelledby="deleteCommentModalLabel" aria-hidden='true'>
            <div class='modal-dialog' role="document">
              <div class='modal-content'>
                <div class='modal-header'>
                  <h5 class='modal-title' id='deleteModalLabel'> 
                    Are You Sure?
                  </h5>
                  <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class='modal-body'>
                  <del>{{comment|linebreaks}}</del>
                  <!-- del태그로 감싸면 취소선이 나타난다 -->
                </div>
                <div class='modal-footer'>
                  <button type='button' class='btn btn-secondary' data-dismiss='modal'>Cancel</button>
                  <a role='button' href="/blog/delete_comment/{{comment.pk}}" class="btn btn-danger">Delete</a>
                  <!-- 버튼을 클릭하면 url로 가서 view가 삭제를 처리하도록 도와준다. 그래서 삭제 뷰를 만들어야된다.  -->
                </div>
              </div>
            </div>

          </div>
        </div>
        {% endfor %}
      {% endif %}

    <hr/>

    <!-- Comment with nested comments -->
    <!-- <div class="media mb-4">
      <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
      <div class="media-body">
        <h5 class="mt-0">Commenter Name</h5>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

        <div class="media mt-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <div class="media mt-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

      </div>
    </div>  -->
  </div>
{%endblock%}